name: not_flutter_user
description: Not not-user client side for Flutter
publish_to: 'none'
version: 0.1.1+1
environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2  
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  equatable: ^2.0.3
  not_flutter_manifest:
    git:
      url: https://github.com/interrupter/not_flutter_manifest.git 

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
